# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "omega-maf-prod-terraform-backend-state"
    dynamodb_table = "omega-maf-prod-terraform-backend-lock"
    encrypt        = true
    key            = "me-south-1/./terraform.tfstate"
    region         = "me-south-1"
  }
}
