name: "Terraform Deployment"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    branches: [ SIT ]
defaults:
  run:
    shell: bash
jobs:
  terraform:

    name: 'Terragrunt Initialization, Validation and Apply'
    runs-on: ubuntu-latest

    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: ap-south-1

    steps:
      - name: Terragrunt installation
        run:
           curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
           brew install terragrunt
            
      - name: Checkout
        uses: actions/checkout@v2   #checkout@v2
      
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: true

      - name: Terragrunt Init
        id: init
        run: |
           rm -rf .terragrunt
           terragrunt init -upgrade=true -no-color -input=false

      - name: Terragrunt Format
        id: fmt
        run: |
           terragrunt run-all fmt

      - name: Terragrunt Validate
        id: validate
        run: |
           terragrunt run-all validate

      - name: Terragrunt Plan
        if: github.event_name == 'push' && github.event_name == 'merge_request'
        id: plan
        run: |
          terraform run-all plan
          
      - name: Terragrunt Apply
        if: github.event.pull_request.merged == true
        id: apply
        run: |
           terraform run-all apply -auto-approve
      
      # - name: Terraform destroy
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #      terraform destroy -auto-approve
  
  comment:
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
