name: "Terraform Deployment"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    branches: [ SIT ]
    
defaults:
  run:
    shell: bash
    working-directory: ./system_integration_testing/me-south-1/
    
jobs:
  terraform:

    name: 'Terragrunt Initialization, Validation and Apply'
    runs-on: ubuntu-latest

    env:
         AWS_ACCESS_KEY_ID: AKIAQ7NUSICQGR4WLZ5Z
         AWS_SECRET_ACCESS_KEY: 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
         AWS_DEFAULT_REGION: ap-south-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2   #checkout@v2
        
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: true
          
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.31.10
          
      - name: Interact with Terragrunt
        run: terragrunt --version

      - name: Terragrunt Init
        id: init
        run: |
           ls
           pwd
           terraform init
           #terragrunt init

#       - name: Terragrunt Format
#         id: fmt
#         run: |
#            terragrunt run-all fmt

      - name: Terragrunt Validate
        id: validate
        run: |
           terragrunt run-all validate

      - name: Terragrunt Plan
        if: github.event_name == 'push' && github.event_name == 'merge_request'
        id: plan
        run: |
          terraform run-all plan
          
      - name: Terragrunt Apply
        if: github.event.pull_request.merged == true
        id: apply
        run: |
           terraform run-all apply -auto-approve
      
      # - name: Terraform destroy
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #      terraform destroy -auto-approve
  
  comment:
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
